### ISSUE TITLE
Differents app icon or drawables resources per flavors

### ISSUE THREAD

**Issue by mcvasquez** [saulmm/Gradle-Stuff#1]
Hi,

How I can set differents drawables resources like app icon per flavor in variants.gradle?

**Comment by saulmm** [comment]
Per flavor the proper is to set the right resource folder under your app `src` directory:

```
|---- src
|
|------ flavor1
         |--- res
         |------ drawable
         |--------- custom_drawable.png
|------ flavor2
         |--- res
         |------ drawable
         |--------- custom_drawable.png
```

**Comment by mcvasquez** [comment]
@saulmm, I thought it could be handled from variants.gradle. Thanks for helping me.
